### ISSUE TITLE
[BUG] Website Temporarily Unavailable Due to Authentication Error

### ISSUE THREAD

**Issue by websharkdev** [petermekhaeil/cvai.app#12]
### Description

![image](https://github.com/petermekhaeil/cvai.app/assets/47607282/37f1fa4f-6acb-4b98-b801-08de77216264)

When attempting to access the website, users are encountering an authentication error. This prevents them from accessing the site's content or features.

Error Message:
Error: Authentication Failure

Impact:
The website is currently inaccessible to users, leading to a disruption in user experience and potential loss of traffic or engagement.

### Suggested solution

Steps to Reproduce:

1. Navigate to the website URL.
2. Attempt to access any page or feature on the site.
3. Encounter the authentication error message preventing access.

Expected Behavior:
Users should be able to access the website without encountering any authentication errors.

Additional Information:

- This issue is affecting all users attempting to access the website.
- The error message provides no indication of how users can resolve the authentication issue.
- It's unclear whether this is a temporary issue or if it requires immediate attention from the development team.

### Alternative

Proposed Solution:

- Investigate the cause of the authentication error to determine if it's a temporary issue or a more significant technical issue.
- Implement a fix to resolve the authentication error and restore access to the website for users.
- Communicate with users regarding the status of the website and any steps they need to take on their end, if applicable.

Priority:
High - Given the impact on user accessibility and potential loss of engagement, resolving this issue promptly is crucial to maintain a positive user experience.

**Comment by petermekhaeil** [comment]
Thank you for reporting this - it is now resolved.
