### ISSUE TITLE
Add a history of cover letter generated

### ISSUE THREAD

**Issue by ruchernchong** [petermekhaeil/cvai.app#9]
### Description

For each JD entered and cover letter generated, would be good to find a place to retrieve them.

### Suggested solution

In the accounts page, add a tab or page to display the history of cover letters generated

**Comment by petermekhaeil** [comment]
Thanks for the suggestion @ruchernchong!

PR https://github.com/petermekhaeil/cvai.app/pull/11 adds a "History" page for that lists past generations.

**Comment by ruchernchong** [comment]
Nice new feature!
